import assert from "node:assert/strict";
import test from "node:test";

import {
  adjustMatchInputs,
  predictScore,
} from "../src/liz-model.ts";
import {
  analyticHessian,
  eligibleHistory,
  fitPoissonGlm,
  objectiveGradient,
} from "../src/poisson-glm.ts";

function close(actual, expected, tolerance = 1e-12, label = "value") {
  assert.ok(
    Math.abs(actual - expected) <= tolerance,
    `${label}: expected ${expected}, received ${actual}, delta ${Math.abs(actual - expected)}`,
  );
}

// These were generated by Python Liz 6.1.0a4 ScoreModel.predict(max_goals=16).
const PYTHON_SCORE_GOLDENS = [
  {
    model: "independent",
    inputs: { homeLambda: 1.25, awayLambda: 1.1 },
    metrics: [
      0.39712996236293496,
      0.27909098739191823,
      0.3237790502451466,
      0.4171752074102224,
      0.5828247925897776,
      0.47599328165728,
      4.3520742565306136e-14,
    ],
    top: [
      ["1-1", 0.13113259804638072],
      ["1-0", 0.11921145276943702],
      ["0-1", 0.10490607843710459],
      ["0-0", 0.09536916221554961],
      ["2-1", 0.08195787377898796],
    ],
  },
  {
    model: "liz60",
    inputs: { homeLambda: 1.25, awayLambda: 1.1 },
    metrics: [
      0.3942392893224265,
      0.28441562246120006,
      0.3213450882163735,
      0.41332421464479996,
      0.5866757853552,
      0.47020724930680324,
      4.882760862301438e-13,
    ],
    top: [
      ["1-1", 0.1267380577586774],
      ["1-0", 0.12085616378898287],
      ["0-1", 0.10635342413430496],
      ["0-0", 0.10495313416925911],
      ["2-1", 0.0782466038335949],
    ],
  },
  {
    model: "liz61",
    inputs: { homeLambda: 1.15, awayLambda: 1.1, balancedOpen: true },
    metrics: [
      0.36603696967720467,
      0.2927029241334397,
      0.34126010618935537,
      0.38840026938114003,
      0.61159973061886,
      0.45106345508321577,
      1.3011813848606835e-13,
    ],
    top: [
      ["1-1", 0.1287682830428581],
      ["1-0", 0.1221559706207394],
      ["0-1", 0.11684484146331597],
      ["0-0", 0.11493511106268248],
      ["2-1", 0.0735401391915625],
    ],
  },
];

test("TypeScript Cloud Alpha exact kernel matches Python a4 golden vectors", () => {
  for (const golden of PYTHON_SCORE_GOLDENS) {
    const prediction = predictScore(golden.model, golden.inputs, 16);
    const actual = [
      prediction.homeWin,
      prediction.draw,
      prediction.awayWin,
      prediction.over25,
      prediction.under25,
      prediction.bttsYes,
      prediction.tailMass,
    ];
    actual.forEach((value, index) => close(value, golden.metrics[index], 1e-12, `${golden.model} metric ${index}`));
    prediction.topScores.slice(0, 5).forEach((score, index) => {
      assert.equal(score.score, golden.top[index][0]);
      close(score.probability, golden.top[index][1], 1e-14, `${golden.model} ${score.score}`);
    });
    close(prediction.homeWin + prediction.draw + prediction.awayWin, 1, 5e-15, "1X2 total");
    close(prediction.over25 + prediction.under25, 1, 5e-15, "O/U total");
    close(prediction.bttsYes + prediction.bttsNo, 1, 5e-15, "BTTS total");
  }
});

test("lambda rules preserve T, intersect gates, and fail closed", () => {
  const floor = adjustMatchInputs("liz61", {
    homeLambda: 2,
    awayLambda: 0.2,
    counterUnderdog: "away",
  });
  close(floor.homeLambda, 1.55);
  close(floor.awayLambda, 0.65);
  close(floor.homeLambda + floor.awayLambda, 2.2);
  const intersected = adjustMatchInputs("liz61", {
    homeLambda: 1.5,
    awayLambda: 0.2,
    lowCreativity: "away",
    counterUnderdog: "away",
  });
  assert.ok(intersected.awayLambda >= 0.65 && intersected.awayLambda <= 0.75);
  assert.throws(
    () => adjustMatchInputs("liz61", {
      homeLambda: 0.2,
      awayLambda: 0.2,
      lowCreativity: "away",
      counterUnderdog: "away",
    }),
    /infeasible/,
  );
});

function fixture(fixtureId, timestamp, homeTeamId, awayTeamId, homeGoals90, awayGoals90) {
  return { fixtureId, timestamp, homeTeamId, awayTeamId, homeGoals90, awayGoals90 };
}

test("T-60 plus three-hour result buffer is enforced at the exact boundary", () => {
  const { history, cutoffTimestamp } = eligibleHistory(
    [fixture(1, 5_600, 1, 2, 1, 0), fixture(2, 5_601, 1, 2, 9, 9)],
    20_000,
  );
  assert.deepEqual(history.map((row) => row.fixtureId), [1]);
  assert.equal(cutoffTimestamp, 16_400);
});

test("GLM analytic gradient and Hessian match central differences", () => {
  const theta = [0.1, 0.2, 0.03, -0.04, 0.01, -0.02, 0.05, -0.03];
  const design = {
    homeIndex: [0, 1, 2],
    awayIndex: [1, 2, 0],
    homeGoals: [1, 2, 0],
    awayGoals: [0, 1, 1],
    weights: [1, 0.8, 0.6],
    ridge: 25,
  };
  const { gradient } = objectiveGradient(theta, design);
  const step = 1e-6;
  for (let index = 0; index < theta.length; index += 1) {
    const plus = [...theta];
    const minus = [...theta];
    plus[index] += step;
    minus[index] -= step;
    const numerical = (objectiveGradient(plus, design).objective - objectiveGradient(minus, design).objective) / (2 * step);
    close(gradient[index], numerical, 1e-6, `gradient ${index}`);
  }
  const hessian = analyticHessian(theta, design);
  const hessianStep = 1e-5;
  for (let column = 0; column < theta.length; column += 1) {
    const plus = [...theta];
    const minus = [...theta];
    plus[column] += hessianStep;
    minus[column] -= hessianStep;
    const plusGradient = objectiveGradient(plus, design).gradient;
    const minusGradient = objectiveGradient(minus, design).gradient;
    for (let row = 0; row < theta.length; row += 1) {
      close(hessian[row][column], (plusGradient[row] - minusGradient[row]) / (2 * hessianStep), 1e-6, `hessian ${row},${column}`);
    }
  }
});

test("deterministic Newton GLM matches Python a4 synthetic golden and neutral cold start", () => {
  const fixtures = [];
  const timestamp = 1_000_000;
  for (let index = 0; index < 30; index += 1) {
    fixtures.push(fixture(
      index + 1,
      timestamp + index * 20_000,
      1 + (index % 3),
      1 + ((index + 1) % 3),
      index % 3,
      (index + 1) % 2,
    ));
  }
  const target = timestamp + 31 * 20_000;
  const fit = fitPoissonGlm(fixtures, target, [99, 100], { lambdaMax: 10 });
  const reversed = fitPoissonGlm([...fixtures].reverse(), target, [99, 100], { lambdaMax: 10 });
  assert.equal(fit.converged, true);
  assert.equal(fit.cloudKernel, "Liz6.1 TypeScript Cloud Alpha");
  assert.equal(fit.eligibleFixtureCount, 30);
  assert.equal(fit.cutoffTimestamp, 1_616_400);
  assert.equal(fit.maximumAvailableAt, 1_590_800);
  assert.deepEqual(fit.teamIds, [1, 2, 3, 99, 100]);
  close(fit.mu, -0.7025876080130248, 2e-7, "mu");
  close(fit.homeAdvantage, 0.6420282263075173, 2e-7, "home advantage");
  const regular = fit.predict(1, 2);
  close(regular.homeLambda, 0.6034735114458758, 2e-7, "home lambda");
  close(regular.awayLambda, 0.5871638264206985, 2e-7, "away lambda");
  const cold = fit.predict(99, 100);
  close(cold.homeLambda, 0.9412378750485738, 2e-7, "cold home lambda");
  close(cold.awayLambda, 0.4953019967440228, 2e-7, "cold away lambda");
  close(cold.homeLambda, Math.exp(fit.mu + fit.homeAdvantage), 1e-14);
  close(cold.awayLambda, Math.exp(fit.mu), 1e-14);
  close(reversed.mu, fit.mu, 1e-12, "order-independent mu");
  close(reversed.homeAdvantage, fit.homeAdvantage, 1e-12, "order-independent home advantage");
  assert.ok(fit.gradientInfNorm <= fit.config.gradientTolerance);
  close(fit.diagnostics.ridgePenalty, 25, 1e-12, "ridge penalty");
});

test("prediction lambda release gates fail closed", () => {
  const fixtures = [];
  for (let index = 0; index < 12; index += 1) {
    fixtures.push(fixture(index + 1, 1_000 + index * 20_000, 1, 2, 6, 0));
  }
  assert.throws(() => {
    const strict = fitPoissonGlm(fixtures, 300_000, [1, 2], { lambdaMax: 1 });
    strict.predict(1, 2);
  }, /outside release gate/);
});
